### ISSUE TITLE
HorseBreakSpeed Mixin Conflict 

### ISSUE THREAD

**Issue by Azzyypaaras** [CodeF53/Horse-Buff#43]
My gay ass has been notified of a little funny bit of mixin ya got. You're messing with breaking speed, with a redirect.

![image](https://github.com/CodeF53/Horse-Buff/assets/20349662/d9008fc6-c54f-4785-bf6d-e7ef8d11ecab)

Now, as you may have noticed, shit's crashing - partly because I didn't notice ModifyConstants are redirects in a clown mask that's my bad. But also partly because _your_ gay ass (note: your ass is neither as gay nor as fat as mine, don't get any ideas) just decided to slam a redirect into the middle of PlayerEntity.

Please, consider changing this, ideally for an Inject. Given that I just rewrote Spectrum's two ModifyConstants into a singular return inject, I heavily doubt you actually need the thing -

![image](https://github.com/CodeF53/Horse-Buff/assets/20349662/5524de00-f37c-48d6-9107-334ae7508e0b)

Oh god fucking dammit it is a ModifyConstant too you poor soul - alright listen, just switch it out to an inject that looks like this and you'll be a cheery lil camper. and I'll be able to go girlboss gatekeep gaslighting every twink I find.

![image](https://github.com/CodeF53/Horse-Buff/assets/20349662/81633a01-9456-460e-a64b-ca190084ecf9)

Have a nice whatever time of day it may be, and remember, do _not_ go into the penis explosion chamber, your penis _will_ be exploded.

**Comment by DaFuqs** [comment]
I have come to inform you that @Azzyypaaras has brain damage.
Since [two Inject(at=Return) mixins do not stack](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyReturnValue) mods should use MixinExtras [ModifyReturnValue](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyReturnValue) instead. Which _does_ stack, if >1 mod wants to modify the returns of the same method.

[Unskillissued example](https://github.com/DaFuqs/Spectrum/commit/97cc2ed4a23af54cdf622668a777dfea7bdc30e4)

@Azzyypaaras that's what you get for not being nice to other people. You're going back on the leash and into the cage under the bed. I hope you've learned your lesson, or I'll have to wind up other sites with you. I know a nice shop that sells electric shock collars. (they are kinda fashionable, ngl)

**Comment by CodeF53** [comment]
This is by far the weirdest github issue I have ever received.

I am already familiar with mixinextras and have used it to fix past conflicts. I will fix this when I can be bothered to update the mod again.

**Comment by CodeF53** [comment]
Fixed in 7bbbc28, will be available in 1.19.4+
