### ISSUE TITLE
Remove Fabric API and Cloth Config as depencencies

### ISSUE THREAD

**Issue by CodeF53** [CodeF53/Horse-Buff#9]
I want this mod to be super simple to install to lower the barrier for entry.

By requiring users to download FabricAPI and ClothConfig, that is a inconvenience that may turn someone off from downloading the mod, especially given that ClothConfig isn't even available on modrinth, so users have to go off-platform to get it.

**Comment by CodeF53** [comment]
Example Commit to base changes off of
https://gitlab.com/jeseibel/minecraft-lod-mod/-/compare/0bddc2dcacc760cce5cb0bf9133aab3e001c259e...e83939f1b2e2ecddaed50c818945fbc176561fe6

**Comment by allanonmage** [comment]
Those are 2 prerequisite mods for many many mods, so while I applaud your effort, I think it's mostly moot.  Most mods require one or two of several common library mods, in addition to the dev's own library mod.  THAT is annoying and excessive, but I wouldn't consider Fabric API to be excessive at all, nor really Cloth-Config.

My 2 cents anyways.  I have a spreadsheet for my modpack and keep track of prerequisites for mods to preclude this issue.  My players don't need to worry about it, since I make it easy for them to use the modpack.
